[platformio]
;workspace_dir = C:/.pio-cache/M5Radio
;build_dir = C:/.pio-cache/M5Radio/build
;shared_dir = C:/.pio-cache/M5Radio/shared

[env:m5stack-core-esp32]
platform = espressif32 @ 6.4.0
board = m5stack-core-esp32
framework = arduino

; Принуждаем PlatformIO глубоко искать связанные зависимости (типа WiFiServer для WebServer)
lib_ldf_mode = deep+
 
; 1. Указываем точный объем физической Flash-памяти твоего M5Stack (16MB)
board_upload.flash_size = 16MB
; 2. Принудительно подключаем твою таблицу разделов partitions.csv
board_build.partitions = partitions.csv


build_flags = 
    -O3
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    ; Официальный современный стек библиотек от M5Stack
    m5stack/M5Unified
    m5stack/M5GFX
    earlephilhower/ESP8266Audio @ ^1.9.7
    ; Сетевой асинхронный стек
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    ; Аудио-библиотека (разбита на 2 строки)
;    ; https://github.com/schreibfaul1/ESP32-audioI2S.git#v3.0.0

monitor_speed = 115200
monitor_filters = esp32_exception_decoder