[platformio]
workspace_dir = C:/.pio-cache/M5Radio
build_dir = C:/.pio-cache/M5Radio/build
shared_dir = C:/.pio-cache/M5Radio/shared

[env:m5stack-core-esp32]
platform = espressif32 @ 6.6.0
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200

; Включаем поддержку PSRAM (для версий Gray/Fire) и оптимизацию
build_flags = 
    -DBOARD_HAS_PSRAM 
    -mfix-esp32-psram-cache-issue 
    -DDEBUG_MODE=1 
    -D CORE_DEBUG_LEVEL=1 
    -D CONFIG_SPIRAM_SUPPORT=1
    -D LWIP_CORE_LOCKING=1
    -D LWIP_TCPIP_CORE_LOCKING=1

lib_deps =
    ; Официальный современный стек библиотек от M5Stack
    m5stack/M5Unified @ ^0.2.2
    m5stack/M5GFX @ ^0.2.3
    
    ; Сетевой асинхронный стек
    mathieucarbou/ESPAsyncWebServer @ ^3.6.0

    ; Аудио-библиотека (разбита на 2 строки)
    https://github.com
    schreibfaul1/ESP32-audioI2S.git
